In [1]:
import numpy as np

## Fundamentals

1. https://www.geeksforgeeks.org/python/introduction-to-numpy/

2. https://www.geeksforgeeks.org/numpy/python-numpy/

3. https://www.geeksforgeeks.org/python/numpy-array-in-python/

4. https://www.geeksforgeeks.org/python/basics-of-numpy-arrays/

5. https://www.geeksforgeeks.org/numpy/numpy-ndarray/

6. https://www.geeksforgeeks.org/python/data-type-object-dtype-numpy-python/

1. https://www.geeksforgeeks.org/python/numpy-array-creation/

2. https://www.geeksforgeeks.org/python/numpy-arrange-in-python/

3. https://www.geeksforgeeks.org/numpy/numpy-zeros-python/

4. https://www.geeksforgeeks.org/python/numpy-create-array-filled-with-all-ones/

5. https://www.geeksforgeeks.org/python/numpy-linspace/

6. https://www.geeksforgeeks.org/python/numpy-eye-python/

7. https://www.geeksforgeeks.org/python/creating-a-one-dimensional-numpy-array/

8. https://www.geeksforgeeks.org/numpy/how-to-create-an-empty-and-a-full-numpy-array/

9. https://www.geeksforgeeks.org/python/create-a-numpy-array-filled-with-all-zeros-python/

10. https://www.geeksforgeeks.org/python/how-to-generate-2-d-gaussian-array-using-numpy/

11. https://www.geeksforgeeks.org/python/how-to-create-a-vector-in-python-using-numpy/

12. https://www.geeksforgeeks.org/python/python-numpy-fromrecords-method/

In [2]:
# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
zero_array = np.zeros((1,30))
one_array = np.ones((2,2))
arange_array = np.arange(1,10,2)
                         
print(zero_array)
print(one_array)
print(arange_array)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[1 3 5 7 9]


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#elements from index 1 to 3
print("Range of Elements:",arr[1,:])

#all rows, second column
print("Multidimensional Slicing:", arr[:,1])

Range of Elements: [4 5 6]
Multidimensional Slicing: [2 5]


In [16]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y  
print("Addition:",add)

# Subtraction
subtract = x - y 
print("substration:",subtract)

# Multiplication
multiply = x * y 
print("multiplication:",multiply)

# Division
divide = x / y  
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [21]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [ ]:
# Example array with both positive and negative values
arr = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value
result = np.absolute(arr)
print("Absolute value:", result)

Absolute value: [3 1 0 1 3]


In [15]:
# Two example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Applying a binary operation: addition
result = np.add(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition Result:", result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Addition Result: [5 7 9]


In [17]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [23]:
# Integer datatype
x = np.array([1, 2])  
print(x.dtype)         
 
# Float datatype
x = np.array([1.0, 2.0]) 
print(x.dtype)  
 
# Forced Datatype
x = np.array([1, 2], dtype = np.float64)   
print(x.dtype)

int64
float64
float64


In [20]:
# set alias names for dtypes
dtypes = [('name', 'S20'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik Sharma', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7)
 (b'Hrithik Sharma', 2009, 8.5) (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7)
 (b'Hrithik Sharma', 2009, 8.5) (b'Aakash', 2009, 9. )]


In [24]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [25]:
# Element-wise addition
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)  # Output: [5 7 9]

# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[5 7 9]
[[19 22]
 [43 50]]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [29]:
# i4 represents integer of size 4 byte 
# > represents big-endian byte ordering and < represents little-endian encoding. 
# dt is a dtype object 
dt = np.dtype('>i4') 

print("Byte order is:",dt.byteorder) 

print("Size is:",dt.itemsize) 

print("Data type is:",dt.name)

Byte order is: >
Size is: 4
Data type is: int32


In [30]:
def gaussian_filter(kernel_size, sigma=1, muu=0):
    # Initializing value of x, y as grid of kernel size in the range of kernel size
    x, y = np.meshgrid(np.linspace(-1, 1, kernel_size),
                       np.linspace(-1, 1, kernel_size))
    dst = np.sqrt(x**2 + y**2)

    # Normal part of the Gaussian function
    normal = 1 / (2 * np.pi * sigma**2)

    # Calculating Gaussian filter
    gauss = np.exp(-((dst - muu)**2 / (2.0 * sigma**2))) * normal

    return gauss  # Return the calculated Gaussian filter


# Example usage:
kernel_size = 5
gaussian = gaussian_filter(kernel_size)
print("Gaussian filter of {} X {}:".format(kernel_size, kernel_size))
print(gaussian)

Gaussian filter of 5 X 5:
[[0.05854983 0.0851895  0.09653235 0.0851895  0.05854983]
 [0.0851895  0.12394999 0.14045374 0.12394999 0.0851895 ]
 [0.09653235 0.14045374 0.15915494 0.14045374 0.09653235]
 [0.0851895  0.12394999 0.14045374 0.12394999 0.0851895 ]
 [0.05854983 0.0851895  0.09653235 0.0851895  0.05854983]]


## Array Manipulation

1. https://www.geeksforgeeks.org/python/numpy-copy-and-view/

2. https://www.geeksforgeeks.org/python/how-to-copy-numpy-array-into-another-array/

3. https://www.geeksforgeeks.org/python/appending-values-at-the-end-of-an-numpy-array/

4. https://www.geeksforgeeks.org/python/how-to-swap-columns-of-a-given-numpy-array/

5. https://www.geeksforgeeks.org/python/insert-a-new-axis-within-a-numpy-array/

6. https://www.geeksforgeeks.org/python/numpy-hstack-in-python/

7. https://www.geeksforgeeks.org/python/numpy-vstack-in-python/

8. https://www.geeksforgeeks.org/python/joining-numpy-array/

9. https://www.geeksforgeeks.org/python/combining-a-one-and-a-two-dimensional-numpy-array/

10. https://www.geeksforgeeks.org/python/python-numpy-np-ma-concatenate-method/

11. https://www.geeksforgeeks.org/python/python-numpy-dstack-method/

12. https://www.geeksforgeeks.org/python/splitting-arrays-in-numpy/

13. https://www.geeksforgeeks.org/python/how-to-compare-two-numpy-arrays/

14. https://www.geeksforgeeks.org/python/find-the-union-of-two-numpy-arrays/

15. https://www.geeksforgeeks.org/python/find-unique-rows-in-a-numpy-array/

16. https://www.geeksforgeeks.org/python/python-numpy-np-unique-method/

17. https://www.geeksforgeeks.org/python/numpy-trim_zeros-in-python/


### Copy and View

In [82]:
arr = np.array([2, 4, 6, 8, 10])
v = arr.view()

print("Original ID:", id(arr))
print("View ID:    ", id(v))

arr[0] = 12 

print("Original array:", arr)
print("View array:    ", v)

Original ID: 1943169944048
View ID:     1943169419376
Original array: [12  4  6  8 10]
View array:     [12  4  6  8 10]


In [83]:
arr = np.array([2, 4, 6, 8, 10])
c = arr.copy()

print("Original ID:", id(arr))
print("Copy ID:    ", id(c))

arr[0] = 12
print("Original array:", arr)
print("Copy array:    ", c)

Original ID: 1943168962256
Copy ID:     1943169418128
Original array: [12  4  6  8 10]
Copy array:     [ 2  4  6  8 10]


In [84]:
arr = np.array([2, 4, 6, 8, 10])

nc = arr
print("Original ID:", id(arr))
print("Assigned ID:", id(nc))

nc[0] = 12
print("Original array:", arr)
print("Assigned array:", nc)

Original ID: 1943170269808
Assigned ID: 1943170269808
Original array: [12  4  6  8 10]
Assigned array: [12  4  6  8 10]


In [85]:
arr = np.array([2, 4, 6, 8, 10])

c = arr.copy()
v = arr.view()

print(c.base)
print(v.base)

None
[ 2  4  6  8 10]


### Copy | Append | Insert | Swap

In [86]:
# Creating a numpy array using np.array()
org_array = np.array([1.54, 2.99, 3.42, 4.87, 6.94,
                      8.21, 7.65, 10.50, 77.5])

print("Original array: ")

# printing the Numpy array
print(org_array)

# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)

print("\nCopied array: ")

# printing the copied Numpy array
print(copy_array)

Original array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]

Copied array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]


In [87]:
# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)

# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)

Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7]


In [88]:
arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

combined = np.append(arr, arr_float)
print(combined)  # Output: [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]


In [89]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

combined = np.concatenate((arr1, arr2), axis=0)
# Here 0 represents adding a row
print(combined)

[[1 2]
 [3 4]
 [5 6]]


In [90]:
# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')

# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')

# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [91]:
a = np.arange(12).reshape(4, 3)
print("Original array:\n", a)

print()
print(a[:, [0, 2]])

print()
print(a[:, [2, 0]])

print()
a[:, [0, 2]] = a[:, [2, 0]]
print("After swapping:\n",a)

Original array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]

[[ 2  0]
 [ 5  3]
 [ 8  6]
 [11  9]]

After swapping:
 [[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


### Combining Arrays

numpy.hstack() function stacks arrays in sequence horizontally (column-wise). It joins arrays along their second axis for 2D arrays or flattens and joins them for 1D arrays. This is useful for combining arrays side by side.

In [92]:
a = np.array([[1, 2], [3, 4]])
print(a)

b = np.array([[5, 6], [7, 8]])
print(b)

res = np.hstack((a, b))
print(res)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [93]:
a = np.array([[1, 2], [3, 4]])
print(a)

b = np.array([[5, 6], [7, 8]])
print(b)

res = np.vstack((a, b))
print(res)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


dstack stacks them depth-wise to form a 3D array.

In [94]:
a = np.array([[1, 2], [3, 4]])
print(a)

b = np.array([[5, 6], [7, 8]])
print(b)

res = np.dstack((a, b))
print(res)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


The nditer function in NumPy is an iterator that allows you to efficiently loop through arrays, even if they have different shapes. When you give it two arrays (like 1-D and 2-D), it pairs up their elements side by side and lets you process them together.

In [95]:
num1 = np.array([1, 2,])
num2 = np.array([[10, 20],
                 [30, 40]])
                   
for a, b in np.nditer([num1, num2]):
    print(a, ":", b , "=", a*b)

1 : 10 = 10
2 : 20 = 40
1 : 30 = 30
2 : 40 = 80


np.ma.concatenate() method joins two or more masked arrays along an existing axis. It works similarly to np.concatenate() but it is specifically designed for masked arrays which may contain missing or invalid data that is "masked" i.e marked to be ignored in computations.

In [96]:
a = np.ma.array([1, 2, 3], mask=[0, 1, 0])
b = np.ma.array([4, 5, 6], mask=[0, 0, 1])

res = np.ma.concatenate([a, b])
print(res)

[1 -- 3 4 5 --]


### Other Operations

In [97]:
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(arr, 3)
print(array)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([], shape=(0, 6), dtype=int64)]


In [98]:
# Creating an example array
array = np.arange(6)

# Splitting the array into 2 equal parts along the first axis (axis=0)
result = np.split(array, 2)

print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)

Array:
[0 1 2 3 4 5]

Result after numpy.split():
[array([0, 1, 2]), array([3, 4, 5])]


In [99]:
# Creating a 2D array
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

# Splitting the array into 3 equal parts along the second axis (axis=1)
result = np.split(array, 3, axis=1)

print("2D Array:")
print(array)
print("\nResult after numpy.split() along axis=1:")
print(result)

2D Array:
[[3 2 1]
 [8 9 7]
 [4 6 5]]

Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [100]:
# Creating an example matrix
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

# Vertical splitting into 2 subarrays along axis=0
result = np.vsplit(matrix, 2)

print("Matrix:")
print(matrix)
print("\nResult after numpy.vsplit():")
print(result)

Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Result after numpy.vsplit():
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [101]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

if np.array_equal(arr1, arr2):
    print("Equal")
else:
    print("Not Equal")

Equal


In [102]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

print("Array a:", a)
print("Array b:", b)

print("a > b:", np.greater(a, b))        
print("a >= b:", np.greater_equal(a, b)) 
print("a < b:", np.less(a, b))           
print("a <= b:", np.less_equal(a, b))

Array a: [101  99  87]
Array b: [897  97 111]
a > b: [False  True False]
a >= b: [False  True False]
a < b: [ True False  True]
a <= b: [ True False  True]


In [103]:
a = np.array([10, 20, 30, 40])
b = np.array([20, 40, 60, 80])

res = np.union1d(a,b)
print(res)

[10 20 30 40 60 80]


Finding unique rows means removing duplicate rows from a 2D array so that each row appears only once. For example, given [[1, 2], [3, 4], [1, 2], [5, 6]], the unique rows would be [[1, 2], [3, 4], [5, 6]]. Let’s explore efficient ways to achieve this using NumPy.

In [104]:
a = np.array([1, 2, 2, 3, 4, 4, 4])
res = np.unique(a)
print(res)

[1 2 3 4]


In [105]:
a = np.array([[1, 2], [3, 4], [1, 2], [5, 6]])
res = np.unique(a, axis=0)
print(res)

[[1 2]
 [3 4]
 [5 6]]


In [106]:
a = np.array([0, 0, 3, 4, 0, 5, 0, 0])
res = np.trim_zeros(a)
print(res)

[3 4 0 5]


### Combined Code

In [107]:
# combined_array_ops.py
# Demonstrates copy/view, append, swap columns, newaxis, stacking/joining, splitting,
# comparisons, union/unique/unique-rows, masked concat, and trim_zeros — all at top-level.

import numpy as np

print("\n=== 1) copy vs view ===")
a = np.array([1, 2, 3, 4])
v = a.view()           # view - shared data
c = a.copy()           # deep copy - separate data
print("original a:", a)
v[0] = 99
print("after v[0]=99 -> a (changed because view shares memory):", a)
c[1] = 88
print("after c[1]=88 -> a (unchanged):", a, "c:", c)

print("\n=== 2) copy array into another array (np.copy & slicing) ===")
src = np.arange(6)
dst = np.empty_like(src)
np.copyto(dst, src)    # copyto
print("src:", src)
print("dst after np.copyto:", dst)
# slicing copy example
dst2 = src[:]          # creates a copy for 1-D? actually makes a view for arrays, use .copy() if you want deep copy
dst2 = src.copy()
print("dst2 (src.copy()):", dst2)

print("\n=== 3) append values at end (np.append) ===")
arr = np.array([1, 2, 3])
arr_app = np.append(arr, [4,5])
print("arr:", arr, " after append ->", arr_app)
# for 2D use axis
mat = np.array([[1,2],[3,4]])
mat_app = np.append(mat, [[5,6]], axis=0)
print("mat:\n", mat, "\nmat after append row:\n", mat_app)

print("\n=== 4) swap columns of a given numpy array ===")
M = np.array([[10,20,30],
              [40,50,60]])
print("Before swap:\n", M)
# swap col 0 and 2
M[:, [0,2]] = M[:, [2,0]]
print("After swapping col0 and col2:\n", M)

print("\n=== 5) insert a new axis within a numpy array (np.newaxis / expand_dims) ===")
r = np.array([1,2,3])
print("r shape:", r.shape)
r_row = r[np.newaxis, :]        # shape (1,3)
r_col = r[:, np.newaxis]        # shape (3,1)
print("r_row shape:", r_row.shape, " ->\n", r_row)
print("r_col shape:", r_col.shape, " ->\n", r_col)
# using expand_dims
r_exp = np.expand_dims(r, axis=0)
print("expand_dims axis=0 shape:", r_exp.shape)

print("\n=== 6) np.hstack ===")
a = np.array([1,2,3])
b = np.array([4,5,6])
hs = np.hstack((a, b))
print("hstack 1D:", hs)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("hstack 2D:\n", np.hstack((A,B)))

print("\n=== 7) np.vstack ===")
print("vstack 1D -> stacks as rows:\n", np.vstack((a,b)))
print("vstack 2D:\n", np.vstack((A,B)))

print("\n=== 8) joining arrays (np.concatenate) ===")
print("concatenate along axis=0 (rows):\n", np.concatenate((A,B), axis=0))
print("concatenate along axis=1 (cols):\n", np.concatenate((A,B), axis=1))

print("\n=== 9) combining a one- and a two-dimensional array ===")
one = np.array([9,9])
two = np.array([[1,2],[3,4]])
# to combine, align dimensions (make one into row or column)
one_row = one[np.newaxis, :]      # shape (1,2)
combined_vert = np.vstack((two, one_row))  # now shapes match
print("two:\n", two, "\none_row:\n", one_row, "\ncombined_vert:\n", combined_vert)

print("\n=== 10) np.ma.concatenate (masked-array concatenate) ===")
import numpy.ma as ma
m1 = ma.array([1,2,3])
m2 = ma.array([4,5], mask=[0,1])   # second element masked
mcat = ma.concatenate((m1, m2))
print("m1:", m1, "m2:", m2, "concatenated masked array:", mcat)

print("\n=== 11) np.dstack (depth stack) ===")
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x:\n", x, "\ny:\n", y)
d = np.dstack((x,y))   # stacks along third axis -> shape (2,2,2)
print("dstack -> shape", d.shape, "\n", d)

print("\n=== 12) splitting arrays in numpy (hsplit, vsplit, array_split) ===")
Z = np.arange(12).reshape(3,4)
print("Z:\n", Z)
hleft, hright = np.hsplit(Z, [2])   # split after column 2
print("hsplit into [0:2] and [2:]:\n", hleft, "\n", hright)
vtop, vbottom = np.vsplit(Z, [1])  # split after row 1
print("vsplit into [0:1] and [1:]:\n", vtop, "\n", vbottom)
parts = np.array_split(Z, 3, axis=1)  # flexible split
print("array_split into 3 parts along columns -> lengths:", [p.shape for p in parts])

print("\n=== 13) how to compare two numpy arrays ===")
A1 = np.array([1,2,3])
A2 = np.array([1,2,4])
print("element-wise comparison (A1==A2):", A1 == A2)
print("all elements equal (np.array_equal):", np.array_equal(A1, A2))
print("positions different (np.where):", np.where(A1 != A2))

print("\n=== 14) union of two numpy arrays (np.union1d) ===")
u1 = np.array([1,2,3,3])
u2 = np.array([3,4,5])
print("union1d(u1,u2):", np.union1d(u1, u2))

print("\n=== 15) find unique rows in a numpy array ===")
R = np.array([[1,2],
              [1,2],
              [3,4],
              [3,4],
              [5,6]])
uniq_rows = np.unique(R, axis=0)
print("R:\n", R)
print("unique rows:\n", uniq_rows)

print("\n=== 16) np.unique examples ===")
vals = np.array([1,2,2,3,3,3])
uniq, counts = np.unique(vals, return_counts=True)
print("values:", vals, "unique:", uniq, "counts:", counts)
# unique with return_index, return_inverse
uniq2, idx = np.unique([3,1,2,1,3], return_index=True)
print("unique:", uniq2, "first-occurrence indices:", idx)

print("\n=== 17) np.trim_zeros ===")
z = np.array([0,0,1,2,0,3,0,0])
print("original:", z)
print("trim_zeros (both ends):", np.trim_zeros(z, 'fb'))   # 'f' front, 'b' back, 'fb' both
print("trim_zeros front only:", np.trim_zeros(z, 'f'))
print("trim_zeros back only:", np.trim_zeros(z, 'b'))

print("\n=== Done ===")



=== 1) copy vs view ===
original a: [1 2 3 4]
after v[0]=99 -> a (changed because view shares memory): [99  2  3  4]
after c[1]=88 -> a (unchanged): [99  2  3  4] c: [ 1 88  3  4]

=== 2) copy array into another array (np.copy & slicing) ===
src: [0 1 2 3 4 5]
dst after np.copyto: [0 1 2 3 4 5]
dst2 (src.copy()): [0 1 2 3 4 5]

=== 3) append values at end (np.append) ===
arr: [1 2 3]  after append -> [1 2 3 4 5]
mat:
 [[1 2]
 [3 4]] 
mat after append row:
 [[1 2]
 [3 4]
 [5 6]]

=== 4) swap columns of a given numpy array ===
Before swap:
 [[10 20 30]
 [40 50 60]]
After swapping col0 and col2:
 [[30 20 10]
 [60 50 40]]

=== 5) insert a new axis within a numpy array (np.newaxis / expand_dims) ===
r shape: (3,)
r_row shape: (1, 3)  ->
 [[1 2 3]]
r_col shape: (3, 1)  ->
 [[1]
 [2]
 [3]]
expand_dims axis=0 shape: (1, 3)

=== 6) np.hstack ===
hstack 1D: [1 2 3 4 5 6]
hstack 2D:
 [[1 2 5 6]
 [3 4 7 8]]

=== 7) np.vstack ===
vstack 1D -> stacks as rows:
 [[1 2 3]
 [4 5 6]]
vstack 2D:
 [[1 2]


## Matrix Operations

1. https://www.geeksforgeeks.org/python/matrix-manipulation-python/

2. https://www.geeksforgeeks.org/python/numpy-matrix-operations-empty-function/

3. https://www.geeksforgeeks.org/python/numpy-matrix-operations-zeros-function/

4. https://www.geeksforgeeks.org/python/numpy-matrix-operations-ones-function/

5. https://www.geeksforgeeks.org/python/numpy-matrix-operations-eye-function/

6. https://www.geeksforgeeks.org/python/numpy-matrix-operations-identity-function/

7. https://www.geeksforgeeks.org/python/adding-and-subtracting-matrices-in-python/

8. https://www.geeksforgeeks.org/python/matrix-multiplication-in-numpy/

9. https://www.geeksforgeeks.org/machine-learning/numpy-ndarray-dot-function-python/

10. https://www.geeksforgeeks.org/machine-learning/numpy-vector-multiplication/

11. https://www.geeksforgeeks.org/python/how-to-calculate-dot-product-of-two-vectors-in-python/

12. https://www.geeksforgeeks.org/numpy/multiplication-two-matrices-single-line-using-numpy-python/

13. https://www.geeksforgeeks.org/python/numpy-matrix-transpose-in-python/

14. https://www.geeksforgeeks.org/python/python-numpy-matrix-var/


In [108]:
# combined_simple_matrix_ops.py
# Single-file, top-level script (no functions) demonstrating the requested operations.
# Run with: python combined_simple_matrix_ops.py

print("\n--- np.empty ---")
a_empty = np.empty((2,3))
print(a_empty)   # uninitialized memory (may contain arbitrary values)

print("\n--- np.zeros ---")
a_zeros = np.zeros((2,3))
print(a_zeros)

print("\n--- np.ones ---")
a_ones = np.ones((2,3))
print(a_ones)

print("\n--- np.eye (identity matrix with ones on diagonal) ---")
e = np.eye(3)
print(e)

print("\n--- np.identity ---")
I = np.identity(3)
print(I)

print("\n--- Matrices for arithmetic ---")
A = np.array([[1,2,3],
              [4,5,6]], dtype=float)   # shape (2,3)
B = np.array([[7,8,9],
              [10,11,12]], dtype=float) # shape (2,3)
C = np.array([[1,2],
              [3,4],
              [5,6]], dtype=float)     # shape (3,2)
print("A:\n", A)
print("B:\n", B)
print("C:\n", C)

print("\n--- Add & Subtract (element-wise) ---")
print("A + B:\n", A + B)
print("A - B:\n", A - B)

print("\n--- Element-wise multiplication (Hadamard) ---")
print("A * B:\n", A * B)
print("np.multiply(A, B):\n", np.multiply(A, B))

print("\n--- Matrix multiplication ---")
# A (2x3) @ C (3x2) -> (2x2)
print("A @ C:\n", A @ C)
print("np.matmul(A, C):\n", np.matmul(A, C))
print("np.dot(A, C):\n", np.dot(A, C))   # same for 2D arrays

print("\n--- Vector dot product / vector multiplication ---")
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("v1 dot v2 (np.dot):", np.dot(v1, v2))
print("v1 @ v2:", v1 @ v2)

print("\n--- Multiplying matrix and vector (broadcasting) ---")
vec = np.array([1,10,100])   # shape (3,)
print("A * vec (broadcast across rows):\n", A * vec)
# Also matrix-vector product (matrix multiply) using @ with appropriate shapes:
# For A (2x3) and v (3,), A @ v -> shape (2,)
print("A @ v1:\n", A @ v1)

print("\n--- Transpose ---")
print("A.T:\n", A.T)
print("C.T:\n", C.T)

print("\n--- Variance (np.var) ---")
print("np.var(A):", np.var(A))
print("np.var(A, axis=0):", np.var(A, axis=0))
print("np.var(A, axis=1):", np.var(A, axis=1))

print("\n--- Inverse of a square matrix ---")
M = np.array([[4,7],
              [2,6]], dtype=float)
print("M:\n", M)
detM = np.linalg.det(M)
print("det(M):", detM)
if detM != 0:
    Minv = np.linalg.inv(M)
    print("np.linalg.inv(M):\n", Minv)
    print("M @ Minv (should be identity):\n", np.round(M @ Minv, 10))
else:
    print("M is singular and not invertible")

print("\n--- Single-line multiplication examples ---")
# elementwise and matrix multiplication in single lines:
print("Elementwise: np.multiply(A, B):\n", np.multiply(A, B))
print("Matrix multiply: (A @ C):\n", A @ C)



--- np.empty ---
[[4.9e-324 9.9e-324 9.9e-324]
 [1.5e-323 1.5e-323 1.5e-323]]

--- np.zeros ---
[[0. 0. 0.]
 [0. 0. 0.]]

--- np.ones ---
[[1. 1. 1.]
 [1. 1. 1.]]

--- np.eye (identity matrix with ones on diagonal) ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- np.identity ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- Matrices for arithmetic ---
A:
 [[1. 2. 3.]
 [4. 5. 6.]]
B:
 [[ 7.  8.  9.]
 [10. 11. 12.]]
C:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

--- Add & Subtract (element-wise) ---
A + B:
 [[ 8. 10. 12.]
 [14. 16. 18.]]
A - B:
 [[-6. -6. -6.]
 [-6. -6. -6.]]

--- Element-wise multiplication (Hadamard) ---
A * B:
 [[ 7. 16. 27.]
 [40. 55. 72.]]
np.multiply(A, B):
 [[ 7. 16. 27.]
 [40. 55. 72.]]

--- Matrix multiplication ---
A @ C:
 [[22. 28.]
 [49. 64.]]
np.matmul(A, C):
 [[22. 28.]
 [49. 64.]]
np.dot(A, C):
 [[22. 28.]
 [49. 64.]]

--- Vector dot product / vector multiplication ---
v1 dot v2 (np.dot): 32
v1 @ v2: 32

--- Multiplying matrix and vector (broadcasting) ---
A * vec (broadcast 

## Linear Algebra


1. https://www.geeksforgeeks.org/numpy/numpy-linear-algebra/

2. https://www.geeksforgeeks.org/numpy/get-the-qr-factorization-of-a-given-numpy-array/

3. https://www.geeksforgeeks.org/python/how-to-get-the-magnitude-of-a-vector-in-numpy/

4. https://www.geeksforgeeks.org/python/how-to-compute-the-eigenvalues-and-right-eigenvectors-of-a-given-square-array-using-numpy/

5. https://www.geeksforgeeks.org/python/python-numpy-np-eigvals-method/

6. https://www.geeksforgeeks.org/python/how-to-calculate-the-determinant-of-a-matrix-using-numpy/

7.  https://www.geeksforgeeks.org/python/compute-the-inverse-of-a-matrix-using-numpy/


In [110]:
# combined_linear_algebra_ops_clean.py
# Linear Algebra Operations: QR, Norm, Eigenvalues, Eigvals, Determinant, Inverse
# All code is top-level, simple & spaced for readability.

import numpy as np
from numpy import linalg as LA



# ============================================================
# 1) QR FACTORIZATION
# ============================================================

print("\n==================== QR FACTORIZATION ====================\n")

A_qr = np.array([
    [12.0, -51.0,   4.0],
    [ 6.0, 167.0, -68.0],
    [-4.0,  24.0, -41.0]
])

print("Matrix A_qr:\n", A_qr)

Q, R = LA.qr(A_qr)

print("\nQ Matrix:\n", Q)
print("\nR Matrix:\n", R)

print("\nReconstructed (Q @ R):\n", np.round(Q @ R, 10))
print("Is Q orthonormal?:", np.allclose(Q.T @ Q, np.eye(Q.shape[1])))



# ============================================================
# 2) VECTOR MAGNITUDE / NORM
# ============================================================

print("\n==================== VECTOR MAGNITUDE ====================\n")

v = np.array([3.0, -4.0, 12.0])

print("Vector v:", v)
print("Euclidean norm (||v||):", LA.norm(v))
print("1-norm:", LA.norm(v, 1))
print("Infinity norm:", LA.norm(v, np.inf))



# ============================================================
# 3) EIGENVALUES & EIGENVECTORS (np.linalg.eig)
# ============================================================

print("\n==================== EIGENVALUES & EIGENVECTORS ====================\n")

A_eig = np.array([
    [4.0, 2.0],
    [1.0, 3.0]
])

print("Matrix A_eig:\n", A_eig)

eigvals, eigvecs = LA.eig(A_eig)

print("\nEigenvalues:", eigvals)
print("\nRight Eigenvectors (columns):\n", eigvecs)

print("\n-- Verification of A·v = λ·v --")
for i, λ in enumerate(eigvals):
    v = eigvecs[:, i]
    print(f"Eigenpair {i}: ", np.allclose(A_eig @ v, λ * v))



# ============================================================
# 4) EIGENVALUES ONLY (np.linalg.eigvals)
# ============================================================

print("\n==================== EIGENVALUES ONLY ====================\n")

eigvals_only = LA.eigvals(A_eig)
print("eigvals(A_eig):", eigvals_only)



# ============================================================
# 5) DETERMINANT
# ============================================================

print("\n==================== DETERMINANT ====================\n")

detA = LA.det(A_eig)
print("det(A_eig):", detA)



# ============================================================
# 6) INVERSE
# ============================================================

print("\n==================== INVERSE OF MATRIX ====================\n")

if abs(detA) < 1e-12:
    print("Matrix is singular. No inverse exists.")
else:
    Ainv = LA.inv(A_eig)
    print("Inverse of A_eig:\n", Ainv)

    print("\nA @ A^-1 (should be identity):\n", np.round(A_eig @ Ainv, 10))



# ============================================================
# 7) EXTRA: 3x3 EXAMPLE
# ============================================================

print("\n==================== EXTRA: 3x3 MATRIX EXAMPLE ====================\n")

B = np.array([
    [1.0, 2.0, 3.0],
    [0.0, 1.0, 4.0],
    [5.0, 6.0, 0.0]
])

print("Matrix B:\n", B)

print("\nEigenvalues of B:", LA.eigvals(B))
print("det(B):", LA.det(B))

try:
    Binv = LA.inv(B)
    print("\nInverse of B:\n", Binv)
except LA.LinAlgError:
    print("\nB is singular — no inverse exists.")



print("\n==================== DONE ====================\n")



==================== QR FACTORIZATION ====================

Matrix A_qr:
 [[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]

Q Matrix:
 [[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

R Matrix:
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]

Reconstructed (Q @ R):
 [[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]
Is Q orthonormal?: True

==================== VECTOR MAGNITUDE ====================

Vector v: [ 3. -4. 12.]
Euclidean norm (||v||): 13.0
1-norm: 19.0
Infinity norm: 12.0

==================== EIGENVALUES & EIGENVECTORS ====================

Matrix A_eig:
 [[4. 2.]
 [1. 3.]]

Eigenvalues: [5. 2.]

Right Eigenvectors (columns):
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

-- Verification of A·v = λ·v --
Eigenpair 0:  True
Eigenpair 1:  True

==================== EIGENVALUES ONLY ====================

eigvals(A_eig): [5. 2.]

==================== DETERMINANT =========