In [131]:
# Importing required libraries

import numpy as np

### A

In [132]:
# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [133]:
print(x, end='\n\n')
print(y)
print(z)

[1 2 3]

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [134]:
a = np.zeros(30)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [135]:
a = np.zeros([2,10])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [136]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [137]:
b = np.ones([2,10])
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [138]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [139]:
c = np.arange(1,10,2)
print(c)

[1 3 5 7 9]


In [140]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [141]:
print(arr[1][2])

6


In [142]:
print(arr[1,2])

6


In [143]:
print(arr[:,:])

[[1 2 3]
 [4 5 6]]


In [144]:
print(arr[:,1:3])

[[2 3]
 [5 6]]


In [145]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [146]:
add = x+y
print(add)

[5 7 9]


In [147]:
add2 = x+10
print(add2)

[11 12 13]


In [148]:
add3 = (x+10).sum()
print(add3)

36


===================================================================

In [149]:
arr = np.array([-3, -1, 0, 1, 3])

In [150]:
result = np.absolute(arr)
print(result)

[3 1 0 1 3]


In [151]:
add4 = np.add(result,10)
print(add4)

[13 11 10 11 13]


In [152]:
print(np.pi)

3.141592653589793


In [153]:
print(np.sqrt(result[1]))

1.0


In [154]:
print(np.square(result[0]))

9


In [155]:
print(np.exp(result[0]))

20.085536923187668


===================================================================

In [156]:
x = np.array([1, 2])  

In [157]:
print(x.dtype)  

int64


In [158]:
dtypes = [('name', 'S20'), ('grad_year', int), ('cgpa', float)]

values = [('Hrithik Sharma', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes)

print(arr)

[(b'Hrithik Sharma', 2009, 8.5) (b'Ajay', 2008, 8.7)
 (b'Pankaj', 2008, 7.9) (b'Aakash', 2009, 9. )]


In [159]:
print(arr.dtype)

[('name', 'S20'), ('grad_year', '<i8'), ('cgpa', '<f8')]


In [160]:
print(np.sort(arr, order = 'name'))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7)
 (b'Hrithik Sharma', 2009, 8.5) (b'Pankaj', 2008, 7.9)]


In [161]:
print(np.sort(arr, order = ['grad_year', 'cgpa']))

[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7)
 (b'Hrithik Sharma', 2009, 8.5) (b'Aakash', 2009, 9. )]


In [162]:
arr1 = np.array([[4, 7], [2, 6]], dtype = np.float64)

In [163]:
print(arr1)

[[4. 7.]
 [2. 6.]]


===================================================================

In [164]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [165]:
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [166]:
print(np.cross(a,b))

[-4 -4]


C:\Users\himan\AppData\Local\Temp\ipykernel_20160\1460686796.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(a,b))


In [167]:
flattened_arr = a.flatten()
print(flattened_arr)

[1 2 3 4]


In [168]:
matrix_again = flattened_arr.reshape(2,2)
print(matrix_again)

[[1 2]
 [3 4]]


In [169]:
print(a.itemsize)

8


In [170]:
arr2 = np.linspace(1,100,200)
print(arr2)

[  1.           1.49748744   1.99497487   2.49246231   2.98994975
   3.48743719   3.98492462   4.48241206   4.9798995    5.47738693
   5.97487437   6.47236181   6.96984925   7.46733668   7.96482412
   8.46231156   8.95979899   9.45728643   9.95477387  10.45226131
  10.94974874  11.44723618  11.94472362  12.44221106  12.93969849
  13.43718593  13.93467337  14.4321608   14.92964824  15.42713568
  15.92462312  16.42211055  16.91959799  17.41708543  17.91457286
  18.4120603   18.90954774  19.40703518  19.90452261  20.40201005
  20.89949749  21.39698492  21.89447236  22.3919598   22.88944724
  23.38693467  23.88442211  24.38190955  24.87939698  25.37688442
  25.87437186  26.3718593   26.86934673  27.36683417  27.86432161
  28.36180905  28.85929648  29.35678392  29.85427136  30.35175879
  30.84924623  31.34673367  31.84422111  32.34170854  32.83919598
  33.33668342  33.83417085  34.33165829  34.82914573  35.32663317
  35.8241206   36.32160804  36.81909548  37.31658291  37.81407035
  38.31155

In [171]:
x = np.array([1, 2, 3,4])
y = np.array([4, 5, 6])

np.linspace(-1, 1, kernel_size) creates kernel_size values evenly spaced from -1 to 1.

np.meshgrid(...) takes two 1-D arrays and produces two 2-D arrays:

x contains copies of the first array repeated across rows.

y contains copies of the second array repeated across columns.

In [172]:
a,b = np.meshgrid(x,y)

print(np.meshgrid(x,y))
print()
print(a)
print()
print(b)

(array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]]))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


In [173]:
dst = np.sqrt(a**2 + b**2)
print(dst)

[[4.12310563 4.47213595 5.         5.65685425]
 [5.09901951 5.38516481 5.83095189 6.40312424]
 [6.08276253 6.32455532 6.70820393 7.21110255]]


===================================================================

### B

In [174]:
arr = np.array([2, 4, 6, 8, 10])

In [175]:
v = arr.view()
print(v)
arr[0] = 12 
print(v)

[ 2  4  6  8 10]
[12  4  6  8 10]


In [176]:
c = arr.copy()
print(c)

[12  4  6  8 10]


In [177]:
print(id(v))
print(id(arr))
print(id(c))

2421454064592
2421454072368
2421454063536


In [178]:
print(c.base)
print(v.base)
print(arr.base)

# v.base will return same as arr values

None
[12  4  6  8 10]
None


In [179]:
arr = np.array([1, 8, 3, 3, 5])
print(arr)

[1 8 3 3 5]


In [180]:
arr = np.append(arr, [7])
print(arr)

[1 8 3 3 5 7]


In [181]:
arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

In [182]:
combined = np.append(arr, arr_float)
print(combined) 

[1. 2. 3. 4. 5.]


In [183]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6],[7,8]])

In [184]:
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [185]:
combined = np.concatenate((arr1, arr2), axis=1)
print(combined)

[[1 2 5 6]
 [3 4 7 8]]


In [186]:
arr_row = np.append(arr1, arr2, axis=1)
print(arr_row)

[[1 2 5 6]
 [3 4 7 8]]


In [187]:
a = np.arange(12).reshape(4, 3)

In [188]:
print(a[:, [0, 2]])

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [189]:
print(a[: , 0:2])

[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


In [190]:
print(a[:,:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [191]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [192]:
res = np.hstack((a, b))
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [193]:
res = np.vstack((a, b))
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [194]:
# dstack stacks them depth-wise to form a 3D array.

In [195]:
res = np.dstack((a, b))
print(res)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [196]:
num1 = np.array([1, 2,])
num2 = np.array([[10, 20],[30, 40]])

The nditer function in NumPy is an iterator that allows you to efficiently loop through arrays, even if they have different shapes. When you give it two arrays (like 1-D and 2-D), it pairs up their elements side by side and lets you process them together.

In [197]:
for a, b in np.nditer([num1, num2]):
    print(a, ":", b , "=", a*b)

1 : 10 = 10
2 : 20 = 40
1 : 30 = 30
2 : 40 = 80


np.ma.concatenate() method joins two or more masked arrays along an existing axis. It works similarly to np.concatenate() but it is specifically designed for masked arrays which may contain missing or invalid data that is "masked" i.e marked to be ignored in computations.

In [198]:
a = np.ma.array([1, 2, 3], mask=[0, 2, 0])
b = np.ma.array([4, 5, 6], mask=[0, 0, 1])

In [199]:
print(a)
print()
print(b)

[1 -- 3]

[4 5 --]


In [200]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [201]:
a,b = np.array_split(arr, 2)
print(a)
print()
print(b)

[1 2 3]

[4 5 6]


In [202]:
a,b = np.split(arr,2, axis=0)
print(a)
print()
print(b)

[1 2 3]

[4 5 6]


In [203]:
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

In [204]:
a,b,c = np.split(array, 3, axis=0)
print(a)
print()
print(b)
print()
print(c)

[[3 2 1]]

[[8 9 7]]

[[4 6 5]]


In [205]:
a,b,c = np.split(array, 3, axis=1)
print(a)
print()
print(b)
print()
print(c)

[[3]
 [8]
 [4]]

[[2]
 [9]
 [6]]

[[1]
 [7]
 [5]]


In [206]:
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

In [207]:
result = np.vsplit(matrix, 2)
print(result)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [208]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [209]:
# This compares full array
print(np.array_equal(arr1, arr2))

True


In [210]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

In [211]:
# These compare individual elements
print(np.greater(a, b))        
print(np.greater_equal(a, b)) 
print(np.less(a, b))           
print(np.less_equal(a, b))

[False  True False]
[False  True False]
[ True False  True]
[ True False  True]


In [212]:
res = np.union1d(a,b)
print(res)

[ 87  97  99 101 111 897]


In [213]:
res = np.union1d(a,b).reshape(2,3)
print(res)

[[ 87  97  99]
 [101 111 897]]


In [214]:
a = np.array([1, 2, 2, 3, 4, 4, 4])

In [215]:
res = np.unique(a)
print(res)

[1 2 3 4]


In [216]:
a = np.array([[1, 2], [3, 4], [1, 2], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [1 2]
 [5 6]]


In [217]:
# This compare if any 2 entire rows are same
res = np.unique(a, axis=0)
print(res)

[[1 2]
 [3 4]
 [5 6]]


In [218]:
# This compare if any 2 entire columns are same
#res = np.unique(a, axis=1)
print(res)

[[1 2]
 [3 4]
 [5 6]]


In [219]:
a = np.array([0, 0, 3, 4, 0, 5, 0, 0])

In [220]:
res = np.trim_zeros(a)
print(res)

[3 4 0 5]


===================================================================

### C

In [221]:
a_empty = np.empty((2,3))
print(a_empty)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


In [222]:
z = np.eye((6))

In [223]:
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [224]:
I = np.identity(6)
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [225]:
A = np.array([[1,2,3],
              [4,5,6]], dtype=float)   # shape (2,3)

B = np.array([[7,8,9],
              [10,11,12]], dtype=float) # shape (2,3)

C = np.array([[1,2],
              [3,4],
              [5,6]], dtype=float)     # shape (3,2)

In [226]:
print("A:\n", A)
print()
print("B:\n", B)
print()
print("C:\n", C)

A:
 [[1. 2. 3.]
 [4. 5. 6.]]

B:
 [[ 7.  8.  9.]
 [10. 11. 12.]]

C:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [227]:
print(A+B)

[[ 8. 10. 12.]
 [14. 16. 18.]]


In [228]:
print(A@C)

[[22. 28.]
 [49. 64.]]


In [229]:
res = np.dot(A,C)
print(res)

[[22. 28.]
 [49. 64.]]


In [230]:
# Transpose
print(A.T)


[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [231]:
print(np.var(A , axis=0))

[2.25 2.25 2.25]


In [232]:
print(np.var(A , axis=1))

[0.66666667 0.66666667]


In [233]:
print(np.var(A ))

2.9166666666666665


In [234]:
A = A.reshape(3,2)
print(A)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [235]:
# Inverse

M = np.array([[4,7],
              [2,6]], dtype=float)


detM = np.linalg.det(M)

print("det(M):", detM)
print()

if detM != 0:
    Minv = np.linalg.inv(M)
    print(Minv)
    print()
    
    print(np.round(M @ Minv, 10))
    print()

else:
    print("M is singular and not invertible")
    print()


det(M): 10.000000000000002

[[ 0.6 -0.7]
 [-0.2  0.4]]

[[ 1. -0.]
 [ 0.  1.]]



===================================================================

### D

In [236]:
from numpy import linalg as la

In [237]:
arr = np.array([
    [12.0, -51.0,   4.0],
    [ 6.0, 167.0, -68.0],
    [-4.0,  24.0, -41.0]
])

In [238]:
# QR FACTORIZATION

q,r = la.qr(arr)

In [239]:
print(q)
print()
print(r)

[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [240]:
# Reconstruct

print(np.round(q @ r, 10))

[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]


In [241]:
print("Is Q orthonormal?:", np.allclose(q.T @ q, np.eye(q.shape[1])))

Is Q orthonormal?: True


In [242]:
# VECTOR MAGNITUDE / NORM

In [243]:
import math

def magnitude(vector): 
    return math.sqrt(sum(pow(element, 2) for element in vector))

In [244]:
v = np.array([0, 1, 2, 3, 4])
print('Vector:', v)

Vector: [0 1 2 3 4]


In [245]:

print(magnitude(v))

5.477225575051661


In [246]:
# Method 2
v = np.array([3.0, -4.0, 12.0])

print(v)
print()


print("Euclidean norm (||v||):", la.norm(v))
print("1-norm:", la.norm(v, 1))
print("Infinity norm:", la.norm(v, np.inf))

[ 3. -4. 12.]

Euclidean norm (||v||): 13.0
1-norm: 19.0
Infinity norm: 12.0


In [247]:
# EIGENVALUES & EIGENVECTORS

A_eig = np.array([
    [4.0, 2.0],
    [1.0, 3.0]
])

In [248]:
eigvals, eigvecs = la.eig(A_eig)

In [249]:
print("\nEigenvalues:", eigvals)


Eigenvalues: [5. 2.]


In [250]:

print("\nRight Eigenvectors (columns):\n", eigvecs)


Right Eigenvectors (columns):
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [251]:
print("\n-- Verification of A·v = λ·v --")
for i, λ in enumerate(eigvals):
    v = eigvecs[:, i]
    print(f"Eigenpair {i}: ", np.allclose(A_eig @ v, λ * v))


-- Verification of A·v = λ·v --
Eigenpair 0:  True
Eigenpair 1:  True


In [252]:
eigvals_only = la.eigvals(A_eig)
print("eigvals(A_eig):", eigvals_only)

eigvals(A_eig): [5. 2.]


In [253]:
detA = la.det(A_eig)
print("det(A_eig):", detA)

det(A_eig): 10.000000000000002


In [254]:
print("\n==================== INVERSE OF MATRIX ====================\n")

if abs(detA) < 1e-12:
    print("Matrix is singular. No inverse exists.")
else:
    Ainv = la.inv(A_eig)
    print("Inverse of A_eig:\n", Ainv)

    print("\nA @ A^-1 (should be identity):\n", np.round(A_eig @ Ainv, 10))


==================== INVERSE OF MATRIX ====================

Inverse of A_eig:
 [[ 0.3 -0.2]
 [-0.1  0.4]]

A @ A^-1 (should be identity):
 [[ 1.  0.]
 [-0.  1.]]


===================================================================

### E

In [255]:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])

print("A:", A)
print("B:", B)

A: [10 20 30 40]
B: [1 2 3 4]


In [256]:
# ---- Arithmetic operations ----
print("\nArithmetic:")
print("A + B    ->", A + B)       # element-wise addition
print("A - B    ->", A - B)       # element-wise subtraction
print("A * B    ->", A * B)       # element-wise multiplication
print("A / B    ->", A / B)       # element-wise division (float)
print("A // B   ->", A // B)      # floor division
print("A % B    ->", A % B)       # remainder / modulus
print("A ** B   ->", A ** B)      # element-wise exponentiation


Arithmetic:
A + B    -> [11 22 33 44]
A - B    -> [ 9 18 27 36]
A * B    -> [ 10  40  90 160]
A / B    -> [10. 10. 10. 10.]
A // B   -> [10 10 10 10]
A % B    -> [0 0 0 0]
A ** B   -> [     10     400   27000 2560000]


In [257]:
C = A.copy()
C += 5                            # in-place addition
print("\nC after C += 5:", C)


C after C += 5: [15 25 35 45]


In [258]:
# ---- Comparisons ----
print("\nComparisons:")
print("A == B ->", A == B)        # equal comparison
print("A != B ->", A != B)        # not equal comparison
print("A > B  ->", A > B)         # greater-than
print("A <= B ->", A <= B)        # less-than-or-equal


Comparisons:
A == B -> [False False False False]
A != B -> [ True  True  True  True]
A > B  -> [ True  True  True  True]
A <= B -> [False False False False]


In [259]:
bool1 = np.array([True, False, True, False])
bool2 = np.array([True, True, False, False])

In [260]:
print("\nLogical operations:")
print("logical_and ->", np.logical_and(bool1, bool2))   # AND
print("logical_or  ->", np.logical_or(bool1, bool2))    # OR
print("logical_xor ->", np.logical_xor(bool1, bool2))   # XOR
print("logical_not(bool1) ->", np.logical_not(bool1))   # NOT


Logical operations:
logical_and -> [ True False False False]
logical_or  -> [ True  True  True False]
logical_xor -> [False  True  True False]
logical_not(bool1) -> [False  True False  True]


In [261]:
# ---- Bitwise operations ----
X = np.array([0b0011, 0b0101])    # integers 3,5
Y = np.array([0b0101, 0b0010])    # integers 5,2

In [262]:
print("\nBitwise operations:")
print("X & Y  ->", np.bitwise_and(X, Y))     # bitwise AND
print("X | Y  ->", np.bitwise_or(X, Y))      # bitwise OR
print("X ^ Y  ->", np.bitwise_xor(X, Y))     # bitwise XOR
print("~X     ->", np.bitwise_not(X))        # bitwise NOT
print("X << 1 ->", np.left_shift(X, 1))      # left shift
print("X >> 1 ->", np.right_shift(X, 1))     # right shift


Bitwise operations:
X & Y  -> [1 0]
X | Y  -> [7 7]
X ^ Y  -> [6 7]
~X     -> [-4 -6]
X << 1 -> [ 6 10]
X >> 1 -> [1 2]


In [263]:
vals = np.array([0.0, 0.5, 1.0, 2.0, 4.0])
print("vals:", vals)

vals: [0.  0.5 1.  2.  4. ]


In [264]:
# ---- Trigonometric ----
print("\nTrigonometric:")
print("np.sin(vals) ->", np.sin(vals))       # sine
print("np.cos(vals) ->", np.cos(vals))       # cosine
print("np.tan(vals) ->", np.tan(vals))       # tangent


Trigonometric:
np.sin(vals) -> [ 0.          0.47942554  0.84147098  0.90929743 -0.7568025 ]
np.cos(vals) -> [ 1.          0.87758256  0.54030231 -0.41614684 -0.65364362]
np.tan(vals) -> [ 0.          0.54630249  1.55740772 -2.18503986  1.15782128]


In [266]:
# ---- Exponential and Logarithm ----
print("\nExponential & Log:")
print("np.exp(vals)         ->", np.exp(vals))             # e^x
print()
print("np.log(vals+1e-12)   ->", np.log(vals+1e-12))       # natural log
print()
print("np.log10(vals+1e-12) ->", np.log10(vals+1e-12))     # log base 10


Exponential & Log:
np.exp(vals)         -> [ 1.          1.64872127  2.71828183  7.3890561  54.59815003]

np.log(vals+1e-12)   -> [-2.76310211e+01 -6.93147181e-01  1.00008890e-12  6.93147181e-01
  1.38629436e+00]

np.log10(vals+1e-12) -> [-1.20000000e+01 -3.01029996e-01  4.34333091e-13  3.01029996e-01
  6.02059991e-01]


In [267]:
# ---- Power and root ----
print("\nPower & Roots:")
print("np.sqrt(vals) ->", np.sqrt(vals))     # square root
print("np.power(vals, 2) ->", np.power(vals, 2)) # x²


Power & Roots:
np.sqrt(vals) -> [0.         0.70710678 1.         1.41421356 2.        ]
np.power(vals, 2) -> [ 0.    0.25  1.    4.   16.  ]


In [268]:
# ---- Rounding functions ----
mixed = np.array([1.2, 2.7, -1.3, -2.8])
print("\nRounding:")
print("np.floor(mixed) ->", np.floor(mixed)) # round down
print("np.ceil(mixed)  ->", np.ceil(mixed))  # round up
print("np.round(mixed) ->", np.round(mixed)) # round to nearest
print("np.trunc(mixed) ->", np.trunc(mixed)) # truncate fraction


Rounding:
np.floor(mixed) -> [ 1.  2. -2. -3.]
np.ceil(mixed)  -> [ 2.  3. -1. -2.]
np.round(mixed) -> [ 1.  3. -1. -3.]
np.trunc(mixed) -> [ 1.  2. -1. -2.]


In [271]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("\nAggregations:")
print("np.sum(arr) ->", np.sum(arr))         # total sum
print("np.sum(arr, axis=0) ->", np.sum(arr, axis=0))  # column-wise sum
print("np.mean(arr) ->", np.mean(arr))       # mean
print("np.std(arr)  ->", np.std(arr))        # standard deviation
print("np.argmin(arr) ->", np.argmin(arr))   # returns index of min
print("np.argmax(arr) ->", np.argmax(arr))   # returns index of max


Aggregations:
np.sum(arr) -> 21
np.sum(arr, axis=0) -> [5 7 9]
np.mean(arr) -> 3.5
np.std(arr)  -> 1.707825127659933
np.argmin(arr) -> 0
np.argmax(arr) -> 5


In [273]:
# ---- Special functions ----
vals2 = np.array([-10, -1, 0, 1, 10])
print("\nSpecial:")
print(np.clip(vals2, -2, 2))   # limit range
print(np.sign(vals2))                 # sign (-1,0,1)


Special:
[-2 -1  0  1  2]
[-1 -1  0  1  1]


===================================================================

In [274]:
s1 = np.array(["hello", "world", "NumPy"])
s2 = np.array(["!", "!!!", "rocks"])

In [276]:
# ---- Concatenation ----
print("\nConcatenation:")
print(np.char.add(s1, s2))       # element-wise string add
print(np.char.multiply(np.array(["ha","ho"]), 3))          # repeat string


Concatenation:
['hello!' 'world!!!' 'NumPyrocks']
['hahaha' 'hohoho']


In [280]:
# ---- Case conversions & strip ----

print(np.char.upper(s1))           # uppercase
print(np.char.lower(s1))           # lowercase
print(np.char.capitalize(np.array(["numpy array"])))       # capitalize
print(np.char.strip(np.array(["  a "])) )                  # remove whitespace

['HELLO' 'WORLD' 'NUMPY']
['hello' 'world' 'numpy']
['Numpy array']
['a']


In [295]:
# ---- Join, split, replace ----

print(np.char.join(' ', np.array(["a","b","c"])))          # join chars
print()

print(np.char.split(np.array(["one two"])))                # split string
print()

print(np.char.replace(np.array(["foo"]), "o", "0"))        # replace substring

['a' 'b' 'c']

[list(['one', 'two'])]

['f00']


In [ ]:
arr = np.char.array(["one two"])

chars = list(arr[0])

chars_no_space = [c for c in chars if c != ' ']
print(chars_no_space)



['o', 'n', 'e', 't', 'w', 'o']


In [299]:
# ---- Padding & formatting ----
fmt = np.array(["7", "42", "123456"])

print(np.char.zfill(fmt, 5))   # pad with zeros
print(np.char.center(s1, 11, '*'))  # center
print(np.char.ljust(s1, 10))   # left-justify
print(np.char.rjust(s1, 10))   # right-justify

['00007' '00042' '123456']
['***hello***' '***world***' '***NumPy***']
['hello     ' 'world     ' 'NumPy     ']
['     hello' '     world' '     NumPy']


In [307]:
# ---- Searching ----

print(s1)
print()

print(np.char.startswith(s1, "h"))  # starts with
print(np.char.endswith(np.char.lower(s1), "py"))                     # ends with
print(np.char.find(s1, "l"))             # find 1st index where alphabet matches

['hello' 'world' 'NumPy']

[ True False False]
[False False  True]
[ 2  3 -1]


In [319]:
# ---- Convert String to number & number to string ----
nums = np.array([1,2,3])


strs = np.char.mod('%d', nums)        # format numbers to strings
print(strs)
print()

back = strs.astype(int)
print(back)   # convert back

['1' '2' '3']

[1 2 3]


In [323]:
# More examples
str = "---geeksforgeeks---"

# using strip() to delete all '-'
print ( str.strip('-') )

# using lstrip() to delete all trailing '-'
print ( str.lstrip('-') )

# using rstrip() to delete all leading '-'
print ( str.rstrip('-') )

geeksforgeeks
geeksforgeeks---
---geeksforgeeks


===================================================================

In [324]:
import numpy as np
import numpy.ma as ma

In [325]:
# Reshaping

===================================================================

### F

===================================================================