In [2]:
# Importing required libraries

import numpy as np

### A

In [3]:
# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [6]:
print(x, end='\n\n')
print(y)
print(z)

[1 2 3]

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
a = np.zeros(30)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [17]:
a = np.zeros([2,10])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
b = np.ones([2,10])
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
c = np.arange(1,10,2)
print(c)

[1 3 5 7 9]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
print(arr[1][2])

6


In [30]:
print(arr[1,2])

6


In [31]:
print(arr[:,:])

[[1 2 3]
 [4 5 6]]


In [34]:
print(arr[:,1:3])

[[2 3]
 [5 6]]


In [35]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [36]:
add = x+y
print(add)

[5 7 9]


In [38]:
add2 = x+10
print(add2)

[11 12 13]


In [41]:
add3 = (x+10).sum()
print(add3)

36


===================================================================

In [42]:
arr = np.array([-3, -1, 0, 1, 3])

In [44]:
result = np.absolute(arr)
print(result)

[3 1 0 1 3]


In [47]:
add4 = np.add(result,10)
print(add4)

[13 11 10 11 13]


In [48]:
print(np.pi)

3.141592653589793


In [51]:
print(np.sqrt(result[1]))

1.0


In [54]:
print(np.square(result[0]))

9


In [55]:
print(np.exp(result[0]))

20.085536923187668


===================================================================

In [56]:
x = np.array([1, 2])  

In [57]:
print(x.dtype)  

int64


In [58]:
dtypes = [('name', 'S20'), ('grad_year', int), ('cgpa', float)]

values = [('Hrithik Sharma', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes)

print(arr)

[(b'Hrithik Sharma', 2009, 8.5) (b'Ajay', 2008, 8.7)
 (b'Pankaj', 2008, 7.9) (b'Aakash', 2009, 9. )]


In [59]:
print(arr.dtype)

[('name', 'S20'), ('grad_year', '<i8'), ('cgpa', '<f8')]


In [61]:
print(np.sort(arr, order = 'name'))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7)
 (b'Hrithik Sharma', 2009, 8.5) (b'Pankaj', 2008, 7.9)]


In [63]:
print(np.sort(arr, order = ['grad_year', 'cgpa']))

[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7)
 (b'Hrithik Sharma', 2009, 8.5) (b'Aakash', 2009, 9. )]


In [65]:
arr1 = np.array([[4, 7], [2, 6]], dtype = np.float64)

In [66]:
print(arr1)

[[4. 7.]
 [2. 6.]]


===================================================================

In [67]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [68]:
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [69]:
print(np.cross(a,b))

[-4 -4]


C:\Users\himan\AppData\Local\Temp\ipykernel_21080\1460686796.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(a,b))


In [71]:
flattened_arr = a.flatten()
print(flattened_arr)

[1 2 3 4]


In [74]:
matrix_again = flattened_arr.reshape(2,2)
print(matrix_again)

[[1 2]
 [3 4]]


In [75]:
print(a.itemsize)

8


In [77]:
arr2 = np.linspace(1,100,200)
print(arr2)

[  1.           1.49748744   1.99497487   2.49246231   2.98994975
   3.48743719   3.98492462   4.48241206   4.9798995    5.47738693
   5.97487437   6.47236181   6.96984925   7.46733668   7.96482412
   8.46231156   8.95979899   9.45728643   9.95477387  10.45226131
  10.94974874  11.44723618  11.94472362  12.44221106  12.93969849
  13.43718593  13.93467337  14.4321608   14.92964824  15.42713568
  15.92462312  16.42211055  16.91959799  17.41708543  17.91457286
  18.4120603   18.90954774  19.40703518  19.90452261  20.40201005
  20.89949749  21.39698492  21.89447236  22.3919598   22.88944724
  23.38693467  23.88442211  24.38190955  24.87939698  25.37688442
  25.87437186  26.3718593   26.86934673  27.36683417  27.86432161
  28.36180905  28.85929648  29.35678392  29.85427136  30.35175879
  30.84924623  31.34673367  31.84422111  32.34170854  32.83919598
  33.33668342  33.83417085  34.33165829  34.82914573  35.32663317
  35.8241206   36.32160804  36.81909548  37.31658291  37.81407035
  38.31155

In [88]:
x = np.array([1, 2, 3,4])
y = np.array([4, 5, 6])

np.linspace(-1, 1, kernel_size) creates kernel_size values evenly spaced from -1 to 1.

np.meshgrid(...) takes two 1-D arrays and produces two 2-D arrays:

x contains copies of the first array repeated across rows.

y contains copies of the second array repeated across columns.

In [89]:
a,b = np.meshgrid(x,y)

print(np.meshgrid(x,y))
print()
print(a)
print()
print(b)

(array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]]))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


In [91]:
dst = np.sqrt(a**2 + b**2)
print(dst)

[[4.12310563 4.47213595 5.         5.65685425]
 [5.09901951 5.38516481 5.83095189 6.40312424]
 [6.08276253 6.32455532 6.70820393 7.21110255]]


===================================================================

### B

In [92]:
arr = np.array([2, 4, 6, 8, 10])

In [95]:
v = arr.view()
print(v)
arr[0] = 12 
print(v)

[ 2  4  6  8 10]
[12  4  6  8 10]


In [97]:
c = arr.copy()
print(c)

[12  4  6  8 10]


In [98]:
print(id(v))
print(id(arr))
print(id(c))

1451686615280
1451686614896
1451686617392


In [100]:
print(c.base)
print(v.base)
print(arr.base)

# v.base will return same as arr values

None
[12  4  6  8 10]
None


In [104]:
arr = np.array([1, 8, 3, 3, 5])
print(arr)

[1 8 3 3 5]


In [106]:
arr = np.append(arr, [7])
print(arr)

[1 8 3 3 5 7 7]


In [107]:
arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])

In [108]:
combined = np.append(arr, arr_float)
print(combined) 

[1. 2. 3. 4. 5.]


In [113]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6],[7,8]])

In [114]:
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [115]:
combined = np.concatenate((arr1, arr2), axis=1)
print(combined)

[[1 2 5 6]
 [3 4 7 8]]


In [116]:
arr_row = np.append(arr1, arr2, axis=1)
print(arr_row)

[[1 2 5 6]
 [3 4 7 8]]


In [117]:
a = np.arange(12).reshape(4, 3)

In [118]:
print(a[:, [0, 2]])

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [120]:
print(a[: , 0:2])

[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


In [121]:
print(a[:,:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [122]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [123]:
res = np.hstack((a, b))
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [124]:
res = np.vstack((a, b))
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [126]:
# dstack stacks them depth-wise to form a 3D array.

In [127]:
res = np.dstack((a, b))
print(res)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [128]:
num1 = np.array([1, 2,])
num2 = np.array([[10, 20],[30, 40]])

The nditer function in NumPy is an iterator that allows you to efficiently loop through arrays, even if they have different shapes. When you give it two arrays (like 1-D and 2-D), it pairs up their elements side by side and lets you process them together.

In [129]:
for a, b in np.nditer([num1, num2]):
    print(a, ":", b , "=", a*b)

1 : 10 = 10
2 : 20 = 40
1 : 30 = 30
2 : 40 = 80


np.ma.concatenate() method joins two or more masked arrays along an existing axis. It works similarly to np.concatenate() but it is specifically designed for masked arrays which may contain missing or invalid data that is "masked" i.e marked to be ignored in computations.

In [132]:
a = np.ma.array([1, 2, 3], mask=[0, 2, 0])
b = np.ma.array([4, 5, 6], mask=[0, 0, 1])

In [131]:
print(a)
print()
print(b)

[1 -- 3]

[4 5 --]


In [133]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [143]:
a,b = np.array_split(arr, 2)
print(a)
print()
print(b)

[1 2 3]

[4 5 6]


In [149]:
a,b = np.split(arr,2, axis=0)
print(a)
print()
print(b)

[1 2 3]

[4 5 6]


In [138]:
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

In [144]:
a,b,c = np.split(array, 3, axis=0)
print(a)
print()
print(b)
print()
print(c)

[[3 2 1]]

[[8 9 7]]

[[4 6 5]]


In [146]:
a,b,c = np.split(array, 3, axis=1)
print(a)
print()
print(b)
print()
print(c)

[[3]
 [8]
 [4]]

[[2]
 [9]
 [6]]

[[1]
 [7]
 [5]]


In [150]:
matrix = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

In [151]:
result = np.vsplit(matrix, 2)
print(result)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [156]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [160]:
# This compares full array
print(np.array_equal(arr1, arr2))

True


In [158]:
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])

In [ ]:
# These compare individual elements
print(np.greater(a, b))        
print(np.greater_equal(a, b)) 
print(np.less(a, b))           
print(np.less_equal(a, b))

[False  True False]
[False  True False]
[ True False  True]
[ True False  True]


In [165]:
res = np.union1d(a,b)
print(res)

[ 87  97  99 101 111 897]


In [166]:
res = np.union1d(a,b).reshape(2,3)
print(res)

[[ 87  97  99]
 [101 111 897]]


In [167]:
a = np.array([1, 2, 2, 3, 4, 4, 4])

In [168]:
res = np.unique(a)
print(res)

[1 2 3 4]


In [172]:
a = np.array([[1, 2], [3, 4], [1, 2], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [1 2]
 [5 6]]


In [ ]:
# This compare if any 2 entire rows are same
res = np.unique(a, axis=0)
print(res)

[[1 2]
 [3 4]
 [5 6]]


In [174]:
# This compare if any 2 entire columns are same
#res = np.unique(a, axis=1)
print(res)

[[1 2]
 [3 4]
 [1 2]
 [5 6]]


In [175]:
a = np.array([0, 0, 3, 4, 0, 5, 0, 0])

In [176]:
res = np.trim_zeros(a)
print(res)

[3 4 0 5]


===================================================================

### C

===================================================================

### D

===================================================================